#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

NAMESPACE="zookeeper"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

echo "Installing Zookeeper"

# Create namespace
$KUBECTL create namespace "$NAMESPACE" > /dev/null 2>&1 || true
$KUBECTL apply -f https://k8s.io/examples/application/zookeeper/zookeeper.yaml > /dev/null 2>&1 || true

echo "Zookeeper is installed"
